### ISSUE TITLE
Issues with markdownlint

### ISSUE THREAD

**Issue by m-mohr** [stactools-packages/template#68]
In PR #66 markdownlint was added to the template. I created a new repo from this template and now `pre-commit run --all-files` fails for me:

```
markdownlint.............................................................Failed
- hook id: markdownlint
- exit code: 1

/home/mm/.cache/pre-commit/repola6x5wv_/node_env-system/lib/node_modules/markdownlint-cli/markdownlint.js:111
  return files.flat().map(file => ({
               ^

TypeError: files.flat is not a function
    at prepareFileList (/home/mm/.cache/pre-commit/repola6x5wv_/node_env-system/lib/node_modules/markdownlint-cli/markdownlint.js:111:16)
    at Object.<anonymous> (/home/mm/.cache/pre-commit/repola6x5wv_/node_env-system/lib/node_modules/markdownlint-cli/markdownlint.js:255:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
/home/mm/.cache/pre-commit/repola6x5wv_/node_env-system/lib/node_modules/markdownlint-cli/markdownlint.js:111
  return files.flat().map(file => ({
               ^

TypeError: files.flat is not a function
    at prepareFileList (/home/mm/.cache/pre-commit/repola6x5wv_/node_env-system/lib/node_modules/markdownlint-cli/markdownlint.js:111:16)
    at Object.<anonymous> (/home/mm/.cache/pre-commit/repola6x5wv_/node_env-system/lib/node_modules/markdownlint-cli/markdownlint.js:255:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

I'm pretty sure this is due to the fact that I've only nodejs 10.10.0 installed on my machine and I need to upgrade. Nevertheless, shouldn't the environment check that and make sure that the required dev dependencies are included?

Edit: Yes, upgrading to nodejs v18 helps. Still, how can we ensure the dependenicies are up to date?

**Comment by m-mohr** [comment]
Another issue is now that there will be a tendency to ignore files due to some errors that arise naturally:
- README.md contains longer code snippets which are reported as long lines -> so I'm ignoring README.md
- CHANGELOG.md complains about multiple headings with the same content, but that's normal in Changelogs (multiple "Fixed", "Added", "Changed", ... headers) -> so I'm ignoring CHANGELOG.md
- PULL_REQUEST_TEMPLATE.MD is ignored by default

So now it checks files that devs don't touch anyway and are compliant by default (Code of Conduct, issue template, CONTIRBUTING). So overall the usefulness of adding markdownlint is limited, IMHO. I'd consider removing it again.

cc @gadomski

**Comment by gadomski** [comment]
I'm 👍🏽 for fine-tuning the rules. I'd like to keep markdownlint if possible, because I find it is helpful for linting the README at least. W.r.t. the node version, I'm not sure how to make pre-commit verify node version -- maybe the best we can do is a note in the "Developing" section of the README.

**Comment by m-mohr** [comment]
@gadomski You could run:
`$ npx --yes check-node-version --node '>= 11.0'`
The open question is which version to check for. markdownlint doesn't specify it. 10 did not work, 11 adds the missing flat version, but I'm not sure what else might be missing. Maybe go with the latest supported version, which is 14?

**Comment by gadomski** [comment]
> Or maybe add node as dependency to the environment.yml for dev somehow?
This won't solve the issue, because we have (and should continue to include) PyPI only install/development instructions. IMO just putting a note in the Contributing section (https://github.com/stactools-packages/template/blob/8b15971a9f1fae7933b0e45aac8d59188daf5db5/README-template.md?plain=1#L39) should be sufficient, e.g. `node >= 14` is required to run the linting suite.
